const columns = `sales_executive_id,
      sales_executive_name,
      applicant_name,
      mobile_number,
      email_id,
      solar_plant_type,
      solar_system_type,
      plant_size_kw,
      plant_price,
      installation_pincode,
      district,
      site_address,
      site_latitude,
      site_longitude,
      payment_mode,
      advance_payment_mode,
      upi_type,
      margin_money,
      special_finance_required,
      meter_type,
      name_correction_required,
      correct_name,
      load_enhancement_required,
      current_load,
      required_load,
      cot_required,
      cot_type,
      cot_documents,
      building_floor_number,
      structure_type,
      free_shadow_area,
      installation_date_feasible,
      application_status,
      aadhaar_front_url,
      aadhaar_back_url,
      pan_card_url,
      electric_bill_url,
      smart_meter_doc_url,
      cancel_cheque_url,
      bank_details_doc_url,
      cot_death_certificate_url,
      cot_house_papers_url,
      cot_passport_photo_url,
      cot_family_registration_url,
      cot_aadhaar_photos_urls,
      cot_live_to_live_aadhaar_1_url,
      cot_live_to_live_aadhaar_2_url`.split(',').map(c => c.trim());

const values = `sales_executive_id,
      sales_executive_name,
      applicant_name,
      mobile_number,
      email_id,
      solar_plant_type,
      solar_system_type,
      plant_size_kw,
      plant_price,
      installation_pincode,
      district,
      site_address,
      site_latitude,
      site_longitude,
      payment_mode,
      advance_payment_mode,
      upi_type,
      margin_money,
      special_finance_required,
      meter_type,
      name_correction_required,
      correct_name,
      load_enhancement_required,
      current_load,
      required_load,
      cot_required,
      cot_type,
      cot_documents,
      building_floor_number,
      structure_type,
      free_shadow_area,
      installation_date_feasible,
      application_status,
      aadhaar_front_url,
      aadhaar_back_url,
      pan_card_url,
      electric_bill_url,
      smart_meter_doc_url,
      cancel_cheque_url,
      bank_details_doc_url,
      cot_death_certificate_url,
      cot_house_papers_url,
      cot_passport_photo_url,
      cot_family_registration_url,
      cot_aadhaar_photos_urls,
      cot_live_to_live_aadhaar_1_url,
      cot_live_to_live_aadhaar_2_url`.split(',').map(c => c.trim());

console.log('Columns:', columns.length);
console.log('Values:', values.length);
console.log('Match:', columns.length === values.length);

if (columns.length !== values.length) {
  console.log('\nMismatch detected!');
  columns.forEach((col, i) => {
    if (!values[i] || col !== values[i]) {
      console.log(`Position ${i}: Column='${col}' Value='${values[i] || 'MISSING'}'`);
    }
  });
}
